//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NikeStore
{


    public partial class PlaceOrder
    {

        /// <summary>
        /// imgShoe control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlImage imgShoe;

        /// <summary>
        /// lblName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblName;

        /// <summary>
        /// lblBrand control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBrand;

        /// <summary>
        /// lblDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDescription;

        /// <summary>
        /// lblPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPrice;

        /// <summary>
        /// rptSizes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSizes;

        /// <summary>
        /// hiddenShoeId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hiddenShoeId;

        /// <summary>
        /// btnPlaceOrder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;

        /// <summary>
        /// popupImg control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlImage popupImg;

        /// <summary>
        /// popupName control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl popupName;

        /// <summary>
        /// popupPrice control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl popupPrice;
    }
}
